### ISSUE TITLE
1.17.1 error

### ISSUE THREAD

**Issue by AltarRiza** [4drian3d/ClientCatcher#3]
[04:58:44] [Server thread/ERROR]: Could not load 'plugins\ClientCatcher-2.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more

**Comment by 4drian3d** [comment]
Simple **Velocity** plugin
The plugin only works in [Velocity](https://velocitypowered.com/)
